VehicleWebApp/ViewModels/VehicleModelViewModel.cs
using VehicleWebAppService.Models;
using X.PagedList;

namespace VehicleWebApp.ViewModels
{
    public class VehicleModelViewModel
    {
        public VehicleModel VehicleModel { get; set; }
        public VehicleMake VehicleMake { get; set; }
        public IPagedList<VehicleModel> VehicleModels { get; set; }
    }
}

VehicleWebApp/Controllers/CreateController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using VehicleWebAppService.DAL;
using VehicleWebAppService.Models;

namespace VehicleWebApp.Controllers
{
    public class CreateController : Controller
    {
        private readonly VehicleDbContext VehicleDbContext;
        [BindProperty]
        public VehicleMake VehicleMake { get; set; }

        public CreateController(VehicleDbContext vehicleDbContext)
        {
            VehicleDbContext = vehicleDbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost, ActionName("Create")]
        public async Task<IActionResult> Create()
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            await VehicleDbContext.AddAsync(VehicleMake);
            VehicleDbContext.SaveChanges();
            return RedirectToRoute("Index");
        }
     }
}

VehicleWebApp/Controllers/VehicleMakeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using VehicleWebAppService.Models;
using VehicleWebAppService;
using VehicleWebApp.ViewModels;

namespace VehicleWebApp.Controllers
{
    public class VehicleMakeController : Controller
    {
        private readonly VehicleMakeService VehicleMakeService;

        public VehicleMakeController(VehicleMakeService vehicleMakeService)
        {
            VehicleMakeService = vehicleMakeService;
        }

        // GET: VehicleMake
        public async Task<IActionResult> Index(
            string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["IdSortParm"] = string.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewData["NameSortParm"] = sortOrder == "name_asc" ? "name_desc" : "name_asc";
            ViewData["AbrvSortParm"] = sortOrder == "abrv_asc" ? "abrv_desc" : "abrv_asc";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            VehicleMakeViewModel vehicleMakeViewModel = new()
            {
                VehicleMakes = await VehicleMakeService.GetVehicleMakesBy(
                    sortOrder, searchString, pageNumber)
            };
            return View(vehicleMakeViewModel);
        }

        // GET: VehicleMake/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            VehicleMakeViewModel vehicleMakeViewModel = new()
            {
                VehicleMake = await VehicleMakeService.GetVehicleMake(id)
            };
            return View(vehicleMakeViewModel);
        }

        // GET: VehicleMake/Create
        public ViewResult Create()
        {
            return View();
        }

        // POST: VehicleMake/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Name", "Abrv")] VehicleMake vehicleMake)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await VehicleMakeService.AddVehicleMake(vehicleMake);
                    return RedirectToAction("Index");
                } 
            } 
            catch (DbUpdateException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View();
        }

        // GET: VehicleMake/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            VehicleMakeViewModel vehicleMakeViewModel = new()
            {
                VehicleMake = await VehicleMakeService.GetVehicleMake(id)
            }; 
            return View(vehicleMakeViewModel);
        }

        // POST: VehicleMake/Edit/5
        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id, [Bind("Name", "Abrv")] VehicleMake vehicleMake)
        {
            if (id != vehicleMake.VehicleMakeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await VehicleMakeService.UpdateVehicleMake(vehicleMake);
                    return RedirectToAction("Index");
                }
                catch (DbUpdateException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View();
        }

        // GET: VehicleMake/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            VehicleMakeViewModel vehicleMakeViewModel = new()
            {
                VehicleMake = await VehicleMakeService.GetVehicleMake(id)
            };
            return View(vehicleMakeViewModel);
        }

        // POST: VehicleMake/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var vehicleMake = await VehicleMakeService.GetVehicleMake(id);

            if(vehicleMake == null)
            {
                return NotFound();
            }
            try
            {
                await VehicleMakeService.DeleteVehicleMake(id);
                return RedirectToAction("Index");
            }
            catch (DbUpdateException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View();
        }
    }
}

VehicleWebApp/Controllers/VehicleModelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using VehicleWebApp.ViewModels;
using VehicleWebAppService;
using VehicleWebAppService.Models;

namespace VehicleWebApp.Controllers
{
    public class VehicleModelController : Controller
    {
        private readonly VehicleModelService VehicleModelService;

        public VehicleModelController(VehicleModelService vehicleModelService)
        {
            VehicleModelService = vehicleModelService;
        }

        // GET: VehicleModel
        public async Task<IActionResult> Index(
            string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["IdSortParm"] = string.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewData["VehicleMakeNameSortParm"] =
                sortOrder == "veh_make_asc" ? "veh_make_desc" : "veh_make_asc";
            ViewData["VehicleMakeAbrvSortParm"] =
                sortOrder == "veh_abrv_asc" ? "veh_abrv_desc" : "veh_abrv_asc";
            ViewData["ModelSortParm"] =
                sortOrder == "model_asc" ? "model_desc" : "model_asc";
            ViewData["AbrvSortParm"] =
                sortOrder == "abrv_asc" ? "abrv_desc" : "abrv_asc";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            VehicleModelViewModel vehicleModelViewModel = new()
            {
                VehicleModels = await VehicleModelService.GetVehicleModelsBy(
                    sortOrder, searchString, pageNumber)
            };
            return View(vehicleModelViewModel);
        }

        // GET: VehicleModel/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            VehicleModelViewModel vehicleModelViewModel = new()
            {
                VehicleModel = await VehicleModelService.GetVehicleModel(id)
            };
            return View(vehicleModelViewModel);
        }

        // GET: VehicleModel/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.VehicleMakes = new SelectList(await VehicleModelService.
                    GetAllVehicleMakes(), "VehicleMakeId", "Abrv");
            return View();
        }

        // POST: VehicleModelController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VehicleMakeId", "Name", "Abrv")] 
                            VehicleModel vehicleModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await VehicleModelService.AddVehicleModel(vehicleModel);
                    return RedirectToAction("Index");
                }
            }
            catch (DbUpdateException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View();
        }

        // GET: VehicleModel/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            VehicleModelViewModel vehicleModelViewModel = new()
            {
                VehicleModel = await VehicleModelService.GetVehicleModel(id)
            };
            ViewBag.VehicleMakes = new SelectList(await VehicleModelService.
                    GetAllVehicleMakes(), "VehicleMakeId", "Abrv");

            return View(vehicleModelViewModel);
        }

        // POST: VehicleModel/Edit/5
        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id, [Bind("VehicleMakeId", "Name", "Abrv")]
                            VehicleModel vehicleModel)
        {
            if (id != vehicleModel.VehicleModelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await VehicleModelService.UpdateVehicleModel(vehicleModel);
                    return RedirectToAction("Index");
                }
                catch (DbUpdateException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View();
        }

        // GET: VehicleModel/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            VehicleModelViewModel vehicleModelViewModel = new()
            {
                VehicleModel = await VehicleModelService.GetVehicleModel(id)
            };
            return View(vehicleModelViewModel);
        }

        // POST: VehicleModel/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var vehicleModel = await VehicleModelService.GetVehicleModel(id);

            if (vehicleModel == null)
            {
                return NotFound();
            }
            try
            {
                await VehicleModelService.DeleteVehicleModel(id);
                return RedirectToAction("Index");
            }
            catch (DbUpdateException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View();
        }
    }
}

VehicleWebApp/Views/VehicleModel/Create.cshtml
@model VehicleWebApp.ViewModels.VehicleModelViewModel
@{ 
    ViewData["Title"] = "Vehicle model create";
}

<h3>Vehicle model create</h3>

<a asp-controller="VehicleModel" asp-action="Index">
    <i class="fas fa-long-arrow-alt-left"></i> Back to list
</a>

<form method="post" asp-controller="VehicleModel" asp-action="Create" >
    <div asp-validation-summary="All"></div>
    <div class="row">
        <div class="col-md-4 form-group">
            <b>Vehicle make:</b>
            <select class="form-control" 
                asp-for="@Model.VehicleModel.VehicleMakeId" 
                asp-items=@ViewBag.VehicleMakes>
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 form-group">
            <b>Name:</b>
            <input class="form-control" asp-for="@Model.VehicleModel.Name" placeholder="eg. 530xd"/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 form-group">
            <b>Abrv:</b>
            <input class="form-control" asp-for="@Model.VehicleModel.Abrv" placeholder="eg. F10"/>
        </div>
    </div>
    <input class="btn btn-success" type="submit" value="Create" />
</form>

VehicleWebApp/Views/VehicleModel/Delete.cshtml
@model VehicleWebApp.ViewModels.VehicleModelViewModel
@{ 
    ViewData["Title"] = "Vehicle model delete";
}

<h3>Vehicle model delete</h3>
<a asp-controller="VehicleModel" asp-action="Index">
    <i class="fas fa-long-arrow-alt-left"></i> Back to list
</a>

<h6 class="text-danger">Are you sure that you want to delete this vehicle model?</h6>

<div class="row">
    <div class="col-md-4">
        <p>Id: <b>@Model.VehicleModel.VehicleModelId</b></p>
        <p>Name: <b>@Model.VehicleModel.Name</b></p>
        <p>Abrv: <b>@Model.VehicleModel.Abrv</b></p>
        <p>Vehicle make:</p>
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Abrv</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model.VehicleModel.VehicleMake.VehicleMakeId</td>
                    <td>@Model.VehicleModel.VehicleMake.Name</td>
                    <td>@Model.VehicleModel.VehicleMake.Abrv</td>
                    <td>
                        <a asp-controller="VehicleMake" 
                           asp-action="Details" 
                           asp-route-id="@Model.VehicleModel.VehicleMake.VehicleMakeId">
                           Details
                       </a>
                    </td>
                </tr>         
            </tbody>
        </table>
    </div>
</div>

<form method="post" asp-controller="VehicleModel" asp-action="Delete">
    <input type="submit" class="btn btn-danger" value="Delete"/>
</form>

VehicleWebApp/Views/VehicleModel/Details.cshtml
@model VehicleWebApp.ViewModels.VehicleModelViewModel
@{ 
    ViewData["Title"] = "Vehicle model details";
}

<h3>Vehicle model details</h3>
<a asp-controller="VehicleModel" asp-action="Index">
    <i class="fas fa-long-arrow-alt-left"></i> Back to list
</a>

<div class="row">
    <div class="col-md-4">
        <p>Id: <b>@Model.VehicleModel.VehicleModelId</b></p>
        <p>Name: <b>@Model.VehicleModel.Name</b></p>
        <p>Abrv: <b>@Model.VehicleModel.Abrv</b></p>
        
        <p>Vehicle make:</p>
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Abrv</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model.VehicleModel.VehicleMakeId</td>
                    <td>@Model.VehicleModel.VehicleMake.Name</td>
                    <td>@Model.VehicleModel.VehicleMake.Abrv</td>
                    <td>
                        <a asp-controller="VehicleMake" 
                           asp-action="Details" 
                           asp-route-id="@Model.VehicleModel.VehicleMakeId">
                           Details
                       </a>
                    </td>
                </tr>         
            </tbody>
        </table>
         <a class="btn btn-outline-success" asp-controller="VehicleModel" 
                asp-action="Edit" asp-route-id="@Model.VehicleModel.VehicleModelId">
            Edit
        </a>
        <a class="btn btn-outline-danger" asp-controller="VehicleModel" 
                asp-action="Delete" asp-route-id="@Model.VehicleModel.VehicleModelId">
            Delete
        </a>
    </div>
</div>

VehicleWebApp/Views/VehicleModel/Edit.cshtml
@model VehicleWebApp.ViewModels.VehicleModelViewModel
@{ 
    ViewData["Title"] = "Vehicle model edit";
}

<h3>Vehicle model edit</h3>

<a asp-controller="VehicleModel" asp-action="Index">
    <i class="fas fa-long-arrow-alt-left"></i> Back to list
</a>

<form method="post" asp-controller="VehicleModel" asp-action="Edit" >
    <div asp-validation-summary="All"></div>
    <div class="row">
        <div class="col-md-4 form-group">
            <b>Vehicle make:</b>
            <select class="form-control" 
                asp-for="@Model.VehicleModel.VehicleMakeId" 
                asp-items=@ViewBag.VehicleMakes></select>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 form-group">
            <b>Name:</b>
            <input class="form-control" asp-for="@Model.VehicleModel.Name" placeholder="eg. 530xd"/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 form-group">
            <b>Abrv:</b>
            <input class="form-control" asp-for="@Model.VehicleModel.Abrv" placeholder="eg. F10"/>
        </div>
    </div>
    <input class="btn btn-success" type="submit" value="Edit" />
</form>

VehicleWebApp/Views/VehicleModel/Index.cshtml
@model VehicleWebApp.ViewModels.VehicleModelViewModel
@{ 
    ViewData["Title"] = "Vehicle models";
}

<a class="btn btn-success" asp-controller="VehicleModel" asp-action="Create">
    Create new <i class="fas fa-car-alt"></i>
</a>

<form method="get asp-action="Index">
    <div class="form-group">
        <p>
            Filter by Vehicle Make name: <input type="text" name="SearchString" 
                value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-outline-info" />
        </p>
    </div>
</form>

@if (Model == null || Model.VehicleModels.Count == 0)
{
    <p class="text-center">There are currently no vehicle models in database.</p>
} else
{
     <table class="table">
        <thead>
            <tr>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["IdSortParm"]"
                        asp-route-currentFilter="@ViewData["CurrentFilter"]">
                        Id
                    </a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["VehicleMakeNameSortParm"]"
                        asp-route-currentFilter="@ViewData["CurrentFilter"]">
                        Vehicle make name
                    </a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["VehicleMakeAbrvSortParm"]"
                        asp-route-currentFilter="@ViewData["CurrentFilter"]">
                        Vehicle make abrv
                    </a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["ModelSortParm"]"
                        asp-route-currentFilter="@ViewData["CurrentFilter"]">
                        Model name
                    </a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["AbrvSortParm"]"
                        asp-route-currentFilter="@ViewData["CurrentFilter"]">
                        Model abrv
                    </a>
                </th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in @Model.VehicleModels)
                {
                    <tr>
                        <td>@item.VehicleModelId</td>   
                        <td>@item.VehicleMake.Name</td>
                        <td>@item.VehicleMake.Abrv</td>
                        <td>@item.Name</td>
                        <td>@item.Abrv</td>
                        <td>
                            <a asp-controller="VehicleModel" asp-action="Edit" 
                                asp-route-id="@item.VehicleModelId">Edit</a> |
                            <a asp-controller="VehicleModel" asp-action="Details" 
                                asp-route-id="@item.VehicleModelId">Details</a> |
                            <a asp-controller="VehicleModel" asp-action="Delete" 
                                asp-route-id="@item.VehicleModelId">Delete</a>
                        </td>
                    </tr>
                }    
        </tbody>
    </table>   
}
@{
    var prevDisabled = !Model.VehicleModels.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.VehicleModels.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.VehicleModels.PageNumber - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.VehicleModels.PageNumber + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>